/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminProtectedRouteImport } from './routes/admin/_protected'
import { Route as AdminProtectedSharingRouteImport } from './routes/admin/_protected/sharing'
import { Route as AdminProtectedSettingsRouteImport } from './routes/admin/_protected/settings'
import { Route as AdminProtectedMediaRouteImport } from './routes/admin/_protected/media'
import { Route as AdminProtectedLeadsRouteImport } from './routes/admin/_protected/leads'
import { Route as AdminProtectedDashboardRouteImport } from './routes/admin/_protected/dashboard'
import { Route as AdminProtectedChatsRouteImport } from './routes/admin/_protected/chats'
import { Route as AdminProtectedAnalyticsRouteImport } from './routes/admin/_protected/analytics'
import { Route as AdminProtectedProductsIndexRouteImport } from './routes/admin/_protected/products/index'
import { Route as AdminProtectedProductsSlugRouteImport } from './routes/admin/_protected/products/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedSharingRoute = AdminProtectedSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedSettingsRoute = AdminProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedMediaRoute = AdminProtectedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedLeadsRoute = AdminProtectedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedDashboardRoute = AdminProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedChatsRoute = AdminProtectedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedAnalyticsRoute = AdminProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedProductsIndexRoute =
  AdminProtectedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedProductsSlugRoute =
  AdminProtectedProductsSlugRouteImport.update({
    id: '/products/$slug',
    path: '/products/$slug',
    getParentRoute: () => AdminProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/signup': typeof AdminSignupRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/analytics': typeof AdminProtectedAnalyticsRoute
  '/admin/chats': typeof AdminProtectedChatsRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/leads': typeof AdminProtectedLeadsRoute
  '/admin/media': typeof AdminProtectedMediaRoute
  '/admin/settings': typeof AdminProtectedSettingsRoute
  '/admin/sharing': typeof AdminProtectedSharingRoute
  '/admin/products/$slug': typeof AdminProtectedProductsSlugRoute
  '/admin/products/': typeof AdminProtectedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/signup': typeof AdminSignupRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/analytics': typeof AdminProtectedAnalyticsRoute
  '/admin/chats': typeof AdminProtectedChatsRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/leads': typeof AdminProtectedLeadsRoute
  '/admin/media': typeof AdminProtectedMediaRoute
  '/admin/settings': typeof AdminProtectedSettingsRoute
  '/admin/sharing': typeof AdminProtectedSharingRoute
  '/admin/products/$slug': typeof AdminProtectedProductsSlugRoute
  '/admin/products': typeof AdminProtectedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/signup': typeof AdminSignupRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/_protected/analytics': typeof AdminProtectedAnalyticsRoute
  '/admin/_protected/chats': typeof AdminProtectedChatsRoute
  '/admin/_protected/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/_protected/leads': typeof AdminProtectedLeadsRoute
  '/admin/_protected/media': typeof AdminProtectedMediaRoute
  '/admin/_protected/settings': typeof AdminProtectedSettingsRoute
  '/admin/_protected/sharing': typeof AdminProtectedSharingRoute
  '/admin/_protected/products/$slug': typeof AdminProtectedProductsSlugRoute
  '/admin/_protected/products/': typeof AdminProtectedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/products/$slug'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/sharing'
    | '/admin/products/$slug'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/products/$slug'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/sharing'
    | '/admin/products/$slug'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin/_protected'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/products/$slug'
    | '/admin/_protected/analytics'
    | '/admin/_protected/chats'
    | '/admin/_protected/dashboard'
    | '/admin/_protected/leads'
    | '/admin/_protected/media'
    | '/admin/_protected/settings'
    | '/admin/_protected/sharing'
    | '/admin/_protected/products/$slug'
    | '/admin/_protected/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSignupRoute: typeof AdminSignupRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/sharing': {
      id: '/admin/_protected/sharing'
      path: '/sharing'
      fullPath: '/admin/sharing'
      preLoaderRoute: typeof AdminProtectedSharingRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/settings': {
      id: '/admin/_protected/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminProtectedSettingsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/media': {
      id: '/admin/_protected/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminProtectedMediaRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/leads': {
      id: '/admin/_protected/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminProtectedLeadsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/dashboard': {
      id: '/admin/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminProtectedDashboardRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/chats': {
      id: '/admin/_protected/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminProtectedChatsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/analytics': {
      id: '/admin/_protected/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminProtectedAnalyticsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/products/': {
      id: '/admin/_protected/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProtectedProductsIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/products/$slug': {
      id: '/admin/_protected/products/$slug'
      path: '/products/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AdminProtectedProductsSlugRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
  }
}

interface AdminProtectedRouteChildren {
  AdminProtectedAnalyticsRoute: typeof AdminProtectedAnalyticsRoute
  AdminProtectedChatsRoute: typeof AdminProtectedChatsRoute
  AdminProtectedDashboardRoute: typeof AdminProtectedDashboardRoute
  AdminProtectedLeadsRoute: typeof AdminProtectedLeadsRoute
  AdminProtectedMediaRoute: typeof AdminProtectedMediaRoute
  AdminProtectedSettingsRoute: typeof AdminProtectedSettingsRoute
  AdminProtectedSharingRoute: typeof AdminProtectedSharingRoute
  AdminProtectedProductsSlugRoute: typeof AdminProtectedProductsSlugRoute
  AdminProtectedProductsIndexRoute: typeof AdminProtectedProductsIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedAnalyticsRoute: AdminProtectedAnalyticsRoute,
  AdminProtectedChatsRoute: AdminProtectedChatsRoute,
  AdminProtectedDashboardRoute: AdminProtectedDashboardRoute,
  AdminProtectedLeadsRoute: AdminProtectedLeadsRoute,
  AdminProtectedMediaRoute: AdminProtectedMediaRoute,
  AdminProtectedSettingsRoute: AdminProtectedSettingsRoute,
  AdminProtectedSharingRoute: AdminProtectedSharingRoute,
  AdminProtectedProductsSlugRoute: AdminProtectedProductsSlugRoute,
  AdminProtectedProductsIndexRoute: AdminProtectedProductsIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSignupRoute: AdminSignupRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
